name: netflix
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.0
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0
  freezed: ^2.3.5
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  fimber: ^0.7.0
  webview_flutter: ^4.2.2
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.5.0
  shimmer: ^3.0.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^4.0.2
  flutter_multi_formatter: ^2.11.7
  local_auth: ^2.1.6
  flutter_secure_storage: ^8.0.0
  better_player: ^0.0.83
  flutter_countdown_timer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Preahvihear
      fonts:
        - asset: assets/fonts/Preahvihear-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
